### ISSUE TITLE
Heimdal build fails on Debian 8.2 (Jessie)

### ISSUE THREAD

**Issue by robin24** [Arachni/build-scripts#3]
Using the Arachni bootstrap.sh script for building the self contained environments fails while compiling Heimdal with the following output:

```
## (5/12) heimdal
  * Downloading http://www.h5l.org/dist/src/heimdal-1.5.3.tar.gz                           
  * Extracting
  * Cleaning
  * Configuring (LIBRARY_PATH=/usr/src/build-scripts/arachni-build-dir/arachni/system/usr/lib ./configure --prefix=/usr/src/build-scripts/arachni-build-dir/arachni/system/usr)
  * Compiling
Build failed, check /usr/src/build-scripts/arachni-build-dir/arachni/build/logs/heimdal for details.
When you resolve the issue you can run the script again to continue where the process left off.
```

The errors contained in the heimdal log file are as follows:

```
/usr/src/build-scripts/arachni-build-dir/arachni/build/src/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_getspecific'
/usr/src/build-scripts/arachni-build-dir/arachni/build/src/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_key_create'
/usr/src/build-scripts/arachni-build-dir/arachni/build/src/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
Makefile:509: recipe for target 'tc' failed
make[2]: *** [tc] Error 1
make[2]: Leaving directory '/usr/src/build-scripts/arachni-build-dir/arachni/build/src/heimdal-1.5.3/lib/ipc'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/build-scripts/arachni-build-dir/arachni/build/src/heimdal-1.5.3/lib'
Makefile:496: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

pthread is installed using aptitude on the main system, though I'm not sure if the build script will include that in the library paths... Any suggestions for solving this issue would be greatly appreciated!

**Comment by Zapotek** [comment]
I've actually got no idea, I only use these scripts on my build boxes so not much experience past that.
Does it work if you build `heimdal` manually in your system's env?

**Comment by robin24** [comment]
Hi Tasos,
thanks for the quick response!
No problem… Yes, I can manually build it without any problem! So maybe I should try to clone the Arachni repository to my system and try building it by myself, without using the scripts? I would prefer just installing one of the Deb packages, however I’m trying to set this up on a Raspberry Pi 2 and there appears to be no build for the ARMHF architecture… Using the script, would it be possible to setup Arachni without Heimdal? Just curious, because really I don’t require any sort of Kerberos implementation / functionality.
Thanks a lot for any more help!
Robin

**Comment by Zapotek** [comment]
Arachni relies on on PhantomJS 1.9.2 which is only available for x86 so it won't work.

**Comment by Zapotek** [comment]
So, closing this since that platform is not supported, unfortunately.

**Comment by thawkins** [comment]
Getting the same problem on fedora 23 on x86_64 

Using 

 wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash


Getting this at the bottom of the heimdal build log. 

/bin/sh ../../libtool --tag=CC   --mode=link gcc  -Wall -Wmissing-prototypes -Wpointer-arith -Wbad-function-cast -Wmissing-declarations -Wnested-externs  -g -O2   -o libheim-ipcs.la  server.lo common.lo  ../../ba
se/libheimbase.la ../../lib/vers/libvers.la ../../lib/roken/libroken.la -lcrypt    -lresolv  
libtool: link: (cd .libs/libheim-ipcs.lax/libvers.a && ar x "/home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3/lib/ipc/../../lib/vers/.libs/libvers.a")
libtool: link: ar cru .libs/libheim-ipcs.a .libs/server.o .libs/common.o   .libs/libheim-ipcs.lax/libvers.a/print_version.o 
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libheim-ipcs.a
libtool: link: rm -fr .libs/libheim-ipcs.lax
libtool: link: ( cd ".libs" && rm -f "libheim-ipcs.la" && ln -s "../libheim-ipcs.la" "libheim-ipcs.la" )
gcc  -DHAVE_CONFIG_H -I. -I. -I../../include -I../../include  -I../../lib/roken -I../../lib/roken -I/usr/include/et  -D_LARGE_FILES= -Wall -Wmissing-prototypes -Wpointer-arith -Wbad-function-cast -Wmissing-declar
ations -Wnested-externs  -g -O2 -MT tc.o -MD -MP -MF .deps/tc.Tpo -c -o tc.o tc.c
mv -f .deps/tc.Tpo .deps/tc.Po
/bin/sh ../../libtool --tag=CC   --mode=link gcc  -Wall -Wmissing-prototypes -Wpointer-arith -Wbad-function-cast -Wmissing-declarations -Wnested-externs  -g -O2   -o tc tc.o libheim-ipcc.la ../../lib/vers/libvers
.la ../../lib/roken/libroken.la -lcrypt  -lresolv  
libtool: link: gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wbad-function-cast -Wmissing-declarations -Wnested-externs -g -O2 -o .libs/tc tc.o  ./.libs/libheim-ipcc.a /home/thawkins/arachni-build-dir/arachni/b
uild/src/heimdal-1.5.3/base/.libs/libheimbase.so /home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3/lib/roken/.libs/libroken.so ../../lib/vers/.libs/libvers.a ../../lib/roken/.libs/libroken.so -lcry
pt -lresolv -Wl,-rpath -Wl,/home/thawkins/arachni-build-dir/arachni/system/usr/lib
/home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_getspecific'
/home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_key_create'
/home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
Makefile:509: recipe for target 'tc' failed
make[2]: *** [tc] Error 1
make[2]: Leaving directory '/home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3/lib/ipc'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1


[thawkins@timdev05 ~]$ uname -a
Linux timdev05.dev 4.4.6-300.fc23.x86_64 #1 SMP Wed Mar 16 22:10:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[thawkins@timdev05 etc]$ more /etc/fedora-release
Fedora release 23 (Twenty Three)

Latest updates on F23. 

[thawkins@timdev05 ~]$ wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash
--2016-03-31 13:30:30--  https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh
Resolving raw.github.com (raw.github.com)... 103.245.222.133
Connecting to raw.github.com (raw.github.com)|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/Arachni/build-scripts/master/bootstrap.sh [following]
--2016-03-31 13:30:31--  https://raw.githubusercontent.com/Arachni/build-scripts/master/bootstrap.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 103.245.222.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2267 (2.2K) [text/plain]
Saving to: ‘STDOUT’

-                                                    100%[======================================================================================================================>]   2.21K  --.-KB/s    in 0s      

2016-03-31 13:30:32 (902 MB/s) - written to stdout [2267/2267]


               Arachni build bootstrap (experimental)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 It will download and run the build scripts, leaving you with a self-contained
 environment with Arachni and all its dependencies installed in it.

     by Tasos Laskos <tasos.laskos@gmail.com>
-------------------------------------------------------------------------


# Checking for script dependencies
----------------------------------------
  * wget -- OK
  * tar -- OK

# Bootstrapping
----------------------------------------
  * Downloading                           
  * Extracting
  * Starting the build

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

---- No branch/tag specified, defaulting to: experimental

---- No build environment specified, defaulting to: production


               Arachni builder (experimental)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 It will create an environment, download and install all dependencies in it,
 configure it and install Arachni itself in it.

     by Tasos Laskos <tasos.laskos@gmail.com>
-------------------------------------------------------------------------


# Checking for script dependencies
----------------------------------------
  * wget -- OK
  * gcc -- OK
  * g++ -- OK
  * awk -- OK
  * sed -- OK
  * grep -- OK
  * make -- OK
  * expr -- OK
  * perl -- OK
  * tar -- OK
  * bzip2 -- OK
  * unzip -- OK
  * git -- OK
  * python -- OK

---- Building branch/tag: experimental

# (1/6) Creating directories
---------------------------------
  * /home/thawkins/arachni-build-dir/arachni/build/logs
  * /home/thawkins/arachni-build-dir/arachni/build/archives
  * /home/thawkins/arachni-build-dir/arachni/build/src
  * /home/thawkins/arachni-build-dir/arachni/build/tmp
  * /home/thawkins/arachni-build-dir/arachni/bin
  * /home/thawkins/arachni-build-dir/arachni/system/logs/framework
  * /home/thawkins/arachni-build-dir/arachni/system/logs/webui
  * /home/thawkins/arachni-build-dir/arachni/system/gems
  * /home/thawkins/arachni-build-dir/arachni/system/home/arachni
  * /home/thawkins/arachni-build-dir/arachni/system/usr/bin
  * /home/thawkins/arachni-build-dir/arachni/system/usr/include
  * /home/thawkins/arachni-build-dir/arachni/system/usr/info
  * /home/thawkins/arachni-build-dir/arachni/system/usr/lib
  * /home/thawkins/arachni-build-dir/arachni/system/usr/man

# (2/6) Installing dependencies
-----------------------------------
## (1/12) zlib
  * Downloading http://zlib.net/zlib-1.2.8.tar.gz                           
  * Extracting
  * Cleaning
  * Configuring (CFLAGS="-m64" ./configure --prefix=/home/thawkins/arachni-build-dir/arachni/system/usr)
  * Compiling
  * Installing

## (2/12) openssl
  * Downloading http://openssl.org/source/openssl-1.0.1q.tar.gz                           
  * Extracting
  * Cleaning
  * Configuring (./config -I/home/thawkins/arachni-build-dir/arachni/system/usr/include -L/home/thawkins/arachni-build-dir/arachni/system/usr/lib zlib no-asm no-krb5 shared --prefix=/home/thawkins/arachni-build-dir/arachni/system/usr)
  * Compiling
  * Installing

## (3/12) sqlite
  * Downloading http://www.sqlite.org/2015/sqlite-autoconf-3090200.tar.gz                           
  * Extracting
  * Cleaning
  * Configuring (./configure --prefix=/home/thawkins/arachni-build-dir/arachni/system/usr)
  * Compiling
  * Installing

## (4/12) ncurses
  * Downloading http://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.0.tar.gz                           
  * Extracting
  * Cleaning
  * Configuring (CFLAGS=-fPIC ./configure --prefix=/home/thawkins/arachni-build-dir/arachni/system/usr)
  * Compiling
  * Installing

## (5/12) heimdal
  * Downloading http://www.h5l.org/dist/src/heimdal-1.5.3.tar.gz - ,,,,,,,                           
  * Extracting
  * Cleaning
  * Configuring (LIBRARY_PATH=/home/thawkins/arachni-build-dir/arachni/system/usr/lib ./configure --prefix=/home/thawkins/arachni-build-dir/arachni/system/usr)
  * Compiling
Build failed, check /home/thawkins/arachni-build-dir/arachni/build/logs/heimdal for details.
When you resolve the issue you can run the script again to continue where the process left off.

**Comment by Zapotek** [comment]
Can you please try the following?

```
cd /home/thawkins/arachni-build-dir/arachni/build/src/heimdal-1.5.3
make clean
./configure
make
```

Does that work or does it show the same error?

If it shows the error can you please retry with:
```
make clean
./configure -lpthread
make
```

Cheers

**Comment by thawkins** [comment]
Nope neither of those worked

neither did

make clean
./configure --enable-pthread-support
make

Which is listed in the help screens

But this did work

make clean
LDFLAGS="-lpthread" ./configure
make

note you also need to make sure that  "libXt-devel" is installed.

**Comment by Zapotek** [comment]
@thawkins Thanks a lot, I'll play with the build script a bit, see if I can resolve this.

**Comment by Zapotek** [comment]
@thawkins Btw, how is `libXt-devel` involved? Heimdal needing an X11 toolkit seems weird.

**Comment by thawkins** [comment]
Without it you get this error

x11/stringdefs.h: no such file or directory

**Comment by Zapotek** [comment]
I've added the right flag to the script, looking into `libXt-devel`.

**Comment by thawkins** [comment]
I will try it again tomorrow.

**Comment by thawkins** [comment]
It could just be a case of it being included to support an optional
interface, and not actually being used.

**Comment by thawkins** [comment]
I will uninstall it, run it again and pull the exact file and Line that is
throwing the error.

**Comment by 0day29** [comment]
And a log ?
/home/thawkins/arachni-build-dir/arachni/build/logs/heimdal
What did it say....
